# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtail_personalisation', '0012_remove_personalisablepagemetadata_is_segmented'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(db_index=True, editable=False, max_length=64, null=True)),
                ('path', models.URLField(editable=False, max_length=255, null=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='segment',
            name='visit_count',
        ),
        migrations.AddField(
            model_name='segmentvisit',
            name='segments',
            field=models.ManyToManyField(to='wagtail_personalisation.Segment'),
        ),
        migrations.AddField(
            model_name='segmentvisit',
            name='served_segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='served_segment', to='wagtail_personalisation.Segment'),
        ),
        migrations.AddField(
            model_name='segmentvisit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dayrule',
            name='visits',
            field=models.ManyToManyField(to='wagtail_personalisation.SegmentVisit'),
        ),
        migrations.AddField(
            model_name='devicerule',
            name='visits',
            field=models.ManyToManyField(to='wagtail_personalisation.SegmentVisit'),
        ),
        migrations.AddField(
            model_name='queryrule',
            name='visits',
            field=models.ManyToManyField(to='wagtail_personalisation.SegmentVisit'),
        ),
        migrations.AddField(
            model_name='referralrule',
            name='visits',
            field=models.ManyToManyField(to='wagtail_personalisation.SegmentVisit'),
        ),
        migrations.AddField(
            model_name='timerule',
            name='visits',
            field=models.ManyToManyField(to='wagtail_personalisation.SegmentVisit'),
        ),
        migrations.AddField(
            model_name='userisloggedinrule',
            name='visits',
            field=models.ManyToManyField(to='wagtail_personalisation.SegmentVisit'),
        ),
        migrations.AddField(
            model_name='visitcountrule',
            name='visits',
            field=models.ManyToManyField(to='wagtail_personalisation.SegmentVisit'),
        ),
    ]
