# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('wagtail_personalisation', '0012_remove_personalisablepagemetadata_is_segmented'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField(max_length=255, null=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtail_personalisation.Segment')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sessions.Session')),
            ],
        ),
        migrations.AddField(
            model_name='dayrule',
            name='visits',
            field=models.ManyToManyField(to='wagtail_personalisation.SegmentVisit'),
        ),
        migrations.AddField(
            model_name='devicerule',
            name='visits',
            field=models.ManyToManyField(to='wagtail_personalisation.SegmentVisit'),
        ),
        migrations.AddField(
            model_name='queryrule',
            name='visits',
            field=models.ManyToManyField(to='wagtail_personalisation.SegmentVisit'),
        ),
        migrations.AddField(
            model_name='referralrule',
            name='visits',
            field=models.ManyToManyField(to='wagtail_personalisation.SegmentVisit'),
        ),
        migrations.AddField(
            model_name='timerule',
            name='visits',
            field=models.ManyToManyField(to='wagtail_personalisation.SegmentVisit'),
        ),
        migrations.AddField(
            model_name='userisloggedinrule',
            name='visits',
            field=models.ManyToManyField(to='wagtail_personalisation.SegmentVisit'),
        ),
        migrations.AddField(
            model_name='visitcountrule',
            name='visits',
            field=models.ManyToManyField(to='wagtail_personalisation.SegmentVisit'),
        ),
    ]
