# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-06 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0014_auto_20170606_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='visit_count',
        ),
        migrations.AlterField(
            model_name='segmentvisit',
            name='path',
            field=models.URLField(editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='segmentvisit',
            name='session',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
