# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 05:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtail_personalisation', '0015_auto_20170606_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentvisit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
