# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-07 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0016_segmentvisit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentvisit',
            name='session',
            field=models.CharField(db_index=True, editable=False, max_length=64, null=True),
        ),
    ]
