# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0017_auto_20170607_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentvisit',
            name='served_segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='served_segment', to='wagtail_personalisation.Segment'),
        ),
    ]
