# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0018_segmentvisit_served_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentvisit',
            name='segment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtail_personalisation.Segment'),
        ),
    ]
